export const ADD_BRICK = 'add_brick'
export const DEL_BRICK = 'del_brick'
export const GET_BRICK_TREE = 'get_brick_tree'
export const MODIFY_BRICK = 'modify_brick'
// export const CLICK_MENU = 'click_menu'
// export const SUMBIT = 'submit'