export const ADD_BRICK = 'add_brick'
export const DEL_BRICK = 'del_brick'
export const GET_BRICK_TREE = 'get_brick_tree'
export const SUBMIT_BRICK = 'submit_brick'
export const EDIT_BRICK = 'edit_brick'
export const MODIFY_BRICK = 'modify_brick'